// Ported from src/lib/referralCode.ts on the mobile app — same FNV-1a hash so
// codes generated by the mock adapter during earlier phases stay valid once
// the app points at this backend instead.

const HASH_SPACE = 100_000_000;
const CODE_DIGITS = 8;

function hashUserId(userId) {
  let h = 0x811c9dc5;
  for (let i = 0; i < userId.length; i++) {
    h ^= userId.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0) % HASH_SPACE;
}

function digits(n) {
  return String(n).padStart(CODE_DIGITS, '0');
}

function vendorReferralCode(vendorOrUserId) {
  return `GK-VND-${digits(hashUserId(`vn:${vendorOrUserId}`))}`;
}

function agentReferralCode(userId) {
  return `GK-AGT-${digits(hashUserId(`ag:${userId}`))}`;
}

function customerReferralCode(userId) {
  return `GK-CU-${digits(hashUserId(`cu:${userId}`))}`;
}

function employeeReferralCode(employeeOrUserId) {
  return `GK-EMP-${digits(hashUserId(`em:${employeeOrUserId}`))}`;
}

function detectReferralKind(raw) {
  const code = raw.trim().toUpperCase();
  if (code.startsWith('GK-CU-')) return 'customer';
  if (code.startsWith('GK-VND-') || code.startsWith('GK-VN-')) return 'vendor';
  if (code.startsWith('GK-AGT-') || code.startsWith('GK-AG-')) return 'agent';
  if (code.startsWith('GK-EMP-') || code.startsWith('GK-EM-')) return 'employee';
  return null;
}

module.exports = {
  vendorReferralCode,
  agentReferralCode,
  customerReferralCode,
  employeeReferralCode,
  detectReferralKind,
};
