// Mirrors src/lib/api/mock/fixtures/categories.ts on the mobile app so the
// real backend starts with the same catalogue the mock adapter demos.
const categories = [
  { id: 'cat_plumber', slug: 'plumber', name: 'Plumber', description: 'Leaks, fittings, repairs', iconKey: 'wrench', suggestedMinPaise: 30000, suggestedMaxPaise: 200000, active: true, popular: true, tags: ['Tap repair', 'Pipe leak', 'Toilet repair', 'Drain cleaning', 'Geyser fitting', 'Bathroom fitting'] },
  { id: 'cat_electrician', slug: 'electrician', name: 'Electrician', description: 'Wiring, switches, repairs', iconKey: 'bolt', suggestedMinPaise: 30000, suggestedMaxPaise: 250000, active: true, popular: true, tags: ['Switch / socket', 'Wiring', 'MCB / fuse', 'Inverter', 'Lighting', 'Doorbell', 'Power outlet'] },
  { id: 'cat_ac_repair', slug: 'ac-repair', name: 'AC Repair', description: 'Service & gas refill', iconKey: 'snowflake', suggestedMinPaise: 50000, suggestedMaxPaise: 400000, active: true, popular: true, tags: ['Service & clean', 'Gas refill', 'No cooling', 'Window AC', 'Split AC', 'Install / uninstall'] },
  { id: 'cat_fan_repair', slug: 'fan-repair', name: 'Fan Repair', description: 'Ceiling & table fans', iconKey: 'fan', suggestedMinPaise: 20000, suggestedMaxPaise: 100000, active: true, tags: ['Ceiling fan', 'Table fan', 'Exhaust fan', 'Capacitor change', 'Speed regulator'] },
  { id: 'cat_water_purifier', slug: 'water-purifier', name: 'Water Purifier', description: 'Service & filters', iconKey: 'droplet', suggestedMinPaise: 40000, suggestedMaxPaise: 200000, active: true, tags: ['Filter change', 'Annual service', 'RO repair', 'UV repair', 'Membrane'] },
  { id: 'cat_geyser', slug: 'geyser-repair', name: 'Geyser Repair', description: 'Storage & instant geysers', iconKey: 'flame', suggestedMinPaise: 30000, suggestedMaxPaise: 250000, active: true, tags: ['Storage geyser', 'Instant geyser', 'Heating element', 'Thermostat', 'Installation'] },
  { id: 'cat_carpenter', slug: 'carpenter', name: 'Carpenter', description: 'Furniture & fixtures', iconKey: 'hammer', suggestedMinPaise: 30000, suggestedMaxPaise: 500000, active: true, popular: true, tags: ['Door repair', 'Furniture', 'Modular fitting', 'Window', 'Bed', 'Polish'] },
  { id: 'cat_painter', slug: 'painter', name: 'Painter', description: 'Interior & exterior', iconKey: 'brush', suggestedMinPaise: 100000, suggestedMaxPaise: 2000000, active: true, popular: true, tags: ['Interior', 'Exterior', 'Wood polish', 'Wall texture', 'Touch-up'] },
  { id: 'cat_pest_control', slug: 'pest-control', name: 'Pest Control', description: 'Cockroach, termite, mosquito', iconKey: 'bug', suggestedMinPaise: 80000, suggestedMaxPaise: 500000, active: true, tags: ['Cockroach', 'Termite', 'Mosquito', 'Bedbug', 'Rodent', 'General'] },
  { id: 'cat_house_cleaning', slug: 'house-cleaning', name: 'House Cleaning', description: 'Deep & regular cleaning', iconKey: 'sparkles', suggestedMinPaise: 80000, suggestedMaxPaise: 500000, active: true, popular: true, tags: ['Deep clean', 'Full house', 'Kitchen', 'Move-in / out', 'Post-renovation'] },
  { id: 'cat_bathroom_cleaning', slug: 'bathroom-cleaning', name: 'Bathroom Cleaning', description: 'Deep bathroom cleaning', iconKey: 'shower', suggestedMinPaise: 50000, suggestedMaxPaise: 200000, active: true, tags: ['Deep clean', 'Tiles', 'Grout', 'Sanitisation'] },
  { id: 'cat_sofa_cleaning', slug: 'sofa-carpet-cleaning', name: 'Sofa & Carpet', description: 'Steam & shampoo cleaning', iconKey: 'sofa', suggestedMinPaise: 80000, suggestedMaxPaise: 400000, active: true, tags: ['Sofa shampoo', 'Carpet steam', 'Mattress', 'Stain removal'] },
  { id: 'cat_barber', slug: 'barber-salon', name: 'Barber / Salon', description: 'At-home salon services', iconKey: 'scissors', suggestedMinPaise: 30000, suggestedMaxPaise: 200000, active: true, tags: ['Haircut', 'Beard / shave', 'Hair color', 'Kids haircut'] },
  { id: 'cat_beautician', slug: 'beautician', name: 'Beautician', description: 'Threading, facial, waxing', iconKey: 'lipstick', suggestedMinPaise: 50000, suggestedMaxPaise: 400000, active: true, popular: true, tags: ['Threading', 'Facial', 'Waxing', 'Bleach', 'Manicure', 'Pedicure'] },
  { id: 'cat_massage', slug: 'massage-therapist', name: 'Massage Therapist', description: 'Relaxation & therapy', iconKey: 'spa', suggestedMinPaise: 80000, suggestedMaxPaise: 500000, active: true, tags: ['Relaxation', 'Deep tissue', 'Therapy', 'Couples', 'Ayurvedic'] },
  { id: 'cat_tailor', slug: 'tailor', name: 'Tailor', description: 'Alterations & stitching', iconKey: 'needle', suggestedMinPaise: 10000, suggestedMaxPaise: 200000, active: true, tags: ['Alteration', 'Stitching', 'Embroidery', 'Repair'] },
  { id: 'cat_driver', slug: 'driver', name: 'Driver', description: 'Hourly / outstation', iconKey: 'steering', suggestedMinPaise: 30000, suggestedMaxPaise: 400000, active: true, tags: ['Hourly', 'Outstation', 'Airport drop', 'Wedding', 'Monthly'] },
  { id: 'cat_cook', slug: 'cook', name: 'Cook at Home', description: 'Daily meal prep', iconKey: 'chef', suggestedMinPaise: 50000, suggestedMaxPaise: 300000, active: true, tags: ['North Indian', 'South Indian', 'Vegetarian', 'Non-veg', 'Party menu'] },
  { id: 'cat_maid', slug: 'maid-service', name: 'Maid Service', description: 'Cleaning & utensils', iconKey: 'broom', suggestedMinPaise: 30000, suggestedMaxPaise: 200000, active: true, tags: ['Sweeping', 'Mopping', 'Utensils', 'Laundry', 'Full-time'] },
  { id: 'cat_car_wash', slug: 'car-wash', name: 'Car Wash', description: 'Wash & detailing', iconKey: 'car', suggestedMinPaise: 30000, suggestedMaxPaise: 250000, active: true, tags: ['Exterior wash', 'Interior detailing', 'Polish', 'Foam wash', 'Engine clean'] },
  { id: 'cat_two_wheeler', slug: 'two-wheeler-service', name: 'Two-Wheeler Service', description: 'Bike & scooter service', iconKey: 'motorcycle', suggestedMinPaise: 30000, suggestedMaxPaise: 200000, active: true, tags: ['General service', 'Tyre puncture', 'Battery', 'Brake', 'Chain & oil'] },
  { id: 'cat_appliance', slug: 'appliance-repair', name: 'Appliance Repair', description: 'Washing machine, fridge', iconKey: 'cog', suggestedMinPaise: 30000, suggestedMaxPaise: 400000, active: true, popular: true, tags: ['Washing machine', 'Refrigerator', 'Microwave', 'Chimney', 'Dishwasher', 'Mixer'] },
  { id: 'cat_mobile_laptop', slug: 'mobile-laptop-repair', name: 'Mobile / Laptop', description: 'Screen & board repair', iconKey: 'laptop', suggestedMinPaise: 30000, suggestedMaxPaise: 500000, active: true, tags: ['Screen replacement', 'Battery', 'Board repair', 'Data recovery', 'Software / OS'] },
  { id: 'cat_tutor', slug: 'tutor', name: 'Home Tuition', description: 'School & competitive', iconKey: 'book', suggestedMinPaise: 50000, suggestedMaxPaise: 800000, active: true, tags: ['Maths', 'Science', 'English', 'Hindi', 'Competitive exams', 'Music'] },
];

module.exports = { categories };
